create table if not exists public.eldoria_feedback (
  id bigint generated by default as identity primary key,
  client_event_id uuid not null unique,
  session_id text not null,
  build_name text not null,
  build_version text not null,
  source_commit text not null,
  frozen_commit text,
  kind text not null,
  question_id text not null,
  question text,
  answer text,
  reason text,
  comment text,
  parent_question_id text,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.eldoria_feedback enable row level security;

revoke all on table public.eldoria_feedback from anon;
grant insert on table public.eldoria_feedback to anon;

drop policy if exists "eldoria testers can insert feedback" on public.eldoria_feedback;
create policy "eldoria testers can insert feedback"
on public.eldoria_feedback
for insert
to anon
with check (
  build_name = 'Eldoria Closed Playtest T1'
  and char_length(session_id) between 3 and 64
  and char_length(question_id) between 1 and 120
  and jsonb_typeof(context) = 'object'
);

create index if not exists eldoria_feedback_session_idx on public.eldoria_feedback(session_id, created_at);
create index if not exists eldoria_feedback_question_idx on public.eldoria_feedback(question_id, created_at);
create index if not exists eldoria_feedback_build_idx on public.eldoria_feedback(build_version, created_at);
