(()=>{'use strict';
const C=window.ELDORIA_TESTER_CONFIG||{},QK='eldoria-tester-feedback-queue-v1',IK='eldoria-tester-intro-v1',AK='eldoria-tester-asked-v1',ERR=[];
let last={type:'load',label:'Carga inicial',at:Date.now()},pending=null,finalMounted=false;
const jread=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}},jwrite=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const st=()=>{try{return window.ELDORIA_V023?.state?.()||{}}catch{return{}}},sum=()=>{try{return window.ELDORIA_V023?.sessionSummary?.()||{}}catch{return{}}};
const uid=()=>crypto?.randomUUID?.()||('fb-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));
function context(){const s=st(),m=sum(),sel=document.querySelector('[data-node].selected,[data-poi].selected,.selected[data-node],.selected[data-poi]');return{
testerBuild:C.buildName||'Eldoria Closed Playtest',testerVersion:C.version||'unknown',sourceCommit:C.sourceCommit||'unknown',frozenCommit:C.frozenCommit||null,
gameVersion:window.ELDORIA_V023?.version||document.querySelector('meta[name="eldoria-version"]')?.content||'unknown',sessionId:s.sessionId||m.sessionId||'unknown',
bastion:s.bastionLevel||s.bastion||null,mission:(document.querySelector('[data-testid="mission-active"],.questCard,.goalCard,.missionCard,.objectiveCard')?.innerText||'').trim()||null,
screen:s.view||null,lastAction:last,hero:s.heroSelected||null,power:m?.power?.total??s.power??null,expeditionPower:m?.power?.expedition??null,
resources:{wood:Math.floor(s.wood||0),stone:Math.floor(s.stone||0),food:Math.floor(s.food||0),troops:Math.floor(s.troops||0)},
progression:{chapter:s.chapter||null,bastionLevel:s.bastionLevel||null,sawmill:!!s.sawmill,barracks:!!s.barracks,granary:!!s.granary,stoneworks:!!s.graniteQuarry,forge:!!s.forge,lyra:!!s.lyra,maelis:!!s.maelis,codexUnlocked:!!s.codexUnlocked,duelTutorialComplete:!!s.duelTutorialComplete,fissureDefeated:!!s.boss,devourerDefeated:!!s.devourerDefeated,narethRescued:!!s.narethRescued,trialWon:!!s.trialWon,arc1Complete:!!s.finalWon},
selected:s.selectedAction||sel?.dataset.node||sel?.dataset.poi||null,recentEvents:(window.ELDORIA_V023?.eventLog?.()||[]).slice(-15),recentErrors:ERR.slice(-8),timestamp:new Date().toISOString()}}
function queue(){return jread(QK,[])}
async function send(r){if(typeof window.__ELDORIA_TESTER_SUBMIT__==='function')return !!(await window.__ELDORIA_TESTER_SUBMIT__(r));if(!C.endpoint||!C.anonKey)throw Error('feedback-backend-not-configured');const u=C.endpoint.replace(/\/$/,'')+'/rest/v1/'+encodeURIComponent(C.table||'eldoria_feedback'),x=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json','apikey':C.anonKey,'Authorization':'Bearer '+C.anonKey,'Prefer':'return=minimal'},body:JSON.stringify(r),keepalive:true});if(!x.ok)throw Error('feedback-http-'+x.status);return true}
async function flush(){const q=queue(),left=[];let sent=0;for(const r of q){try{await send(r);sent++}catch{left.push(r)}}jwrite(QK,left);return{sent:sent,pending:left.length}}
async function submit(id,q,a,e){e=e||{};const s=st(),r={client_event_id:uid(),session_id:s.sessionId||sum().sessionId||'unknown',build_name:C.buildName||'Eldoria Closed Playtest',build_version:C.version||'unknown',source_commit:C.sourceCommit||'unknown',frozen_commit:C.frozenCommit||null,kind:e.kind||'question',question_id:id,question:q,answer:a,reason:e.reason||null,comment:e.comment||null,parent_question_id:e.parentQuestionId||null,context:context(),created_at:new Date().toISOString()},z=queue();z.push(r);jwrite(QK,z);await flush();return r}
function styles(){const x=document.createElement('style');x.id='eldoria-tester-style';x.textContent='.testerShade{position:fixed;inset:0;z-index:2147483000;background:#05080bdc;backdrop-filter:blur(7px);display:grid;place-items:center;padding:16px;color:#eee}.testerCard{position:relative;width:min(560px,100%);max-height:88vh;overflow:auto;background:linear-gradient(145deg,#171d22,#0c1014);border:1px solid #d6b66f88;box-shadow:0 25px 90px #000;padding:20px;font-family:Arial,sans-serif}.testerCard h1,.testerCard h2{font-family:Georgia,serif;color:#ead28c;margin:4px 0 10px}.testerCard p{font:14px/1.45 Arial;color:#c9cdd0}.testerEyebrow{font:700 9px Arial;letter-spacing:.16em;color:#d6b66f}.testerActions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:14px}.testerBtn{min-height:44px;border:1px solid #d6b66f88;background:#171d22;color:#f2ead5;padding:10px 12px;font:700 12px Arial;cursor:pointer}.testerBtn.primary{background:linear-gradient(#b0904e,#6d5226);border-color:#efd48d}.testerBtn.negative{border-color:#ba6666}.testerBtn.wide{width:100%;margin-top:12px}.testerClose{position:absolute;right:8px;top:6px;border:0;background:transparent;color:#aaa;font-size:24px}.testerReasons{display:grid;gap:8px;margin-top:12px}.testerSmall{font:11px/1.4 Arial;color:#9ea8ad!important}.testerFeedbackFab{position:fixed;z-index:2147482000;right:8px;bottom:66px;border:1px solid #d6b66f88;background:#0c1116e8;color:#f0dfad;border-radius:18px;min-height:36px;padding:7px 12px;font:700 10px Arial;box-shadow:0 4px 18px #0008;cursor:pointer}.testerFinal{width:min(690px,100%)}.testerFinalQ{padding:10px 0;border-bottom:1px solid #ffffff18}.testerFinalQ b{display:block;margin-bottom:6px;font:13px/1.35 Arial}.testerFinalQ .testerActions{margin-top:0}.testerOpen{display:grid;gap:10px;margin-top:14px}.testerOpen label{font:700 11px Arial;color:#d9c88f}.testerOpen textarea{width:100%;min-height:68px;margin-top:6px;padding:9px;background:#080c10;border:1px solid #ffffff25;color:#fff;font:13px Arial}.testerDone{padding:18px;border:1px solid #77a77755;background:#0f1812;text-align:center}@media(max-width:620px){.testerCard{padding:15px;max-height:86vh}.testerFeedbackFab{right:6px;bottom:62px;min-height:32px;padding:6px 9px;font-size:9px}.testerBtn{min-height:42px}}';document.head.appendChild(x)}
function ov(h,c){const o=document.createElement('div');o.className='testerShade '+(c||'');o.innerHTML=h;document.body.appendChild(o);return o}
function intro(){if(localStorage.getItem(IK)==='1'||new URLSearchParams(location.search).get('skiptesterintro')==='1')return;const o=ov('<section class="testerCard" data-testid="tester-intro"><div class="testerEyebrow">ELDORIA · PRUEBA CERRADA</div><h1>Gracias por probar Eldoria</h1><p>Esta es una versión temprana. El aspecto visual, las animaciones, el equilibrio y parte de la interfaz todavía cambiarán.</p><p><b>No te estamos evaluando a ti: estamos evaluando el juego.</b> Queremos saber si entiendes qué hacer, dónde te pierdes, qué te interesa, qué te aburre y si te apetece continuar.</p><p>Responde con sinceridad. La mayoría de preguntas serán de un solo toque y puedes ignorar las que no quieras contestar.</p><button class="testerBtn primary wide" data-start>EMPEZAR A JUGAR</button></section>');o.querySelector('[data-start]').onclick=()=>{localStorage.setItem(IK,'1');submit('tester_intro','Pantalla inicial de tester','Comenzó',{kind:'system'});o.remove()}}
function amap(){return jread(AK,{})}function asked(id){const s=st(),m=amap();return !!m[(s.sessionId||'unknown')+':'+id]}function mark(id){const s=st(),m=amap();m[(s.sessionId||'unknown')+':'+id]=Date.now();jwrite(AK,m)}
function busy(){return !!document.querySelector('.testerShade,.e22-overlay,.aldric-cinematic,.tutorialDialogue,.tutorialAldric')}
function ask(x){if(asked(x.id)){pending=null;return}if(busy()){pending=x;return}pending=null;mark(x.id);const rs=x.reasons||['No sabía dónde pulsar','No entendí el objetivo','No entendí la recompensa','Otro'],o=ov('<section class="testerCard" data-testid="tester-question-'+x.id+'"><button class="testerClose" aria-label="Cerrar">×</button><div class="testerEyebrow">OPINIÓN RÁPIDA · OPCIONAL</div><h2>'+x.question+'</h2><div class="testerActions"><button class="testerBtn primary" data-a="Sí">'+(x.yes||'Sí')+'</button><button class="testerBtn negative" data-a="No">'+(x.no||'No')+'</button></div><div class="testerReasons" hidden></div></section>');const close=()=>o.remove();o.querySelector('.testerClose').onclick=close;o.querySelectorAll('[data-a]').forEach(b=>b.onclick=async()=>{const a=b.dataset.a;await submit(x.id,x.question,a,{kind:'contextual'});if(a==='Sí'){close();return}const box=o.querySelector('.testerReasons');box.hidden=false;box.innerHTML='<p class="testerSmall">¿Qué fue lo que falló? Puedes omitirlo.</p>'+rs.map((v,i)=>'<button class="testerBtn" data-r="'+i+'">'+v+'</button>').join('')+'<button class="testerBtn" data-skip>OMITIR</button>';box.querySelectorAll('[data-r]').forEach(rb=>rb.onclick=async()=>{const z=rs[Number(rb.dataset.r)];await submit(x.id+':reason','Motivo de respuesta negativa',z,{kind:'followup',parentQuestionId:x.id});close()});box.querySelector('[data-skip]').onclick=close})}
function help(){const q='¿Qué te ocurre?',a=['No sé qué hacer','No encuentro dónde pulsar','No puedo continuar','Algo no funciona','Quiero dejar un comentario'],o=ov('<section class="testerCard" data-testid="tester-blocked"><button class="testerClose">×</button><div class="testerEyebrow">AYUDA / FEEDBACK</div><h2>'+q+'</h2><div class="testerReasons">'+a.map((v,i)=>'<button class="testerBtn" data-h="'+i+'">'+v+'</button>').join('')+'</div><div class="testerOpen" hidden><label>Comentario opcional<textarea maxlength="500" placeholder="Cuéntanos brevemente qué ha pasado"></textarea></label><button class="testerBtn primary">ENVIAR</button></div></section>');o.querySelector('.testerClose').onclick=()=>o.remove();o.querySelectorAll('[data-h]').forEach(b=>b.onclick=async()=>{const z=a[Number(b.dataset.h)];await submit('blocked',q,z,{kind:'blocked'});if(z!=='Quiero dejar un comentario'){o.remove();return}const p=o.querySelector('.testerOpen');p.hidden=false;p.querySelector('button').onclick=async()=>{const c=p.querySelector('textarea').value.trim();if(c)await submit('blocked:comment','Comentario de bloqueo',c,{kind:'comment',comment:c,parentQuestionId:'blocked'});o.remove()}})}
function fab(){if(document.querySelector('.testerFeedbackFab'))return;const b=document.createElement('button');b.className='testerFeedbackFab';b.setAttribute('data-testid','tester-feedback');b.textContent='¿BLOQUEADO?';b.onclick=help;document.body.appendChild(b)}
const F=[['final-understood','¿Entendiste qué hacer durante la mayor parte del juego?'],['final-blocked','¿Te sentiste bloqueado en algún momento?'],['final-combat','¿El combate te resultó comprensible?'],['final-heroes','¿Te interesaron los héroes?'],['final-power','¿Te interesó mejorar tu Poder?'],['final-codex','¿Te interesaron las cartas y el Códice?'],['final-more-cards','¿Te gustaría conseguir más cartas?'],['final-breach','¿La Brecha te generó curiosidad?'],['final-story','¿La historia te dio ganas de saber qué ocurre después?'],['final-continue','¿Seguirías jugando si hubiese más contenido?']];
function final(host){if(finalMounted)return;finalMounted=true;const c=document.createElement('section');c.className='testerCard testerFinal';c.setAttribute('data-testid','tester-final');c.innerHTML='<div class="testerEyebrow">FINAL DEL CONTENIDO · 2 MINUTOS</div><h1>¿Qué te ha parecido Eldoria?</h1><p>Marca Sí o No. Las dos preguntas abiertas del final son opcionales.</p>'+F.map(x=>'<div class="testerFinalQ" data-q="'+x[0]+'"><b>'+x[1]+'</b><div class="testerActions"><button class="testerBtn" data-v="Sí">Sí</button><button class="testerBtn" data-v="No">No</button></div></div>').join('')+'<div class="testerOpen"><label>¿Qué fue lo que más te gustó?<textarea data-open="favorite" maxlength="600"></textarea></label><label>¿Qué cambiarías primero?<textarea data-open="change" maxlength="600"></textarea></label></div><button class="testerBtn primary wide" data-finish>ENVIAR Y TERMINAR</button><p class="testerSmall" data-status></p>';host.innerHTML='';host.appendChild(c);c.querySelectorAll('.testerFinalQ').forEach(r=>r.querySelectorAll('[data-v]').forEach(b=>b.onclick=async()=>{const id=r.dataset.q,q=F.find(x=>x[0]===id)[1],a=b.dataset.v;r.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('primary',x===b));if(r.dataset.sent!==a){r.dataset.sent=a;await submit(id,q,a,{kind:'final'})}}));c.querySelector('[data-finish]').onclick=async()=>{const f=c.querySelector('[data-open="favorite"]').value.trim(),g=c.querySelector('[data-open="change"]').value.trim();if(f)await submit('final-favorite','¿Qué fue lo que más te gustó?',f,{kind:'final-open',comment:f});if(g)await submit('final-change','¿Qué cambiarías primero?',g,{kind:'final-open',comment:g});await submit('final-complete','Encuesta final','Completada',{kind:'system'});const z=await flush();c.innerHTML='<div class="testerDone"><div class="testerEyebrow">GRACIAS</div><h2>Prueba completada</h2><p>Tu feedback ha quedado registrado.</p><p class="testerSmall">'+(z.pending?'Hay respuestas pendientes de sincronizar; se reenviarán al recuperar conexión.':'Respuestas sincronizadas correctamente.')+'</p></div>'}}
function watchFinal(){new MutationObserver(()=>{const h=document.querySelector('[data-testid="playtest-complete"]');if(h&&!h.querySelector('[data-testid="tester-final"]')){finalMounted=false;final(h)}}).observe(document.documentElement,{childList:true,subtree:true})}
function poll(){const s=st();if(!Object.keys(s).length)return;if(pending&&!busy()){const x=pending;pending=null;ask(x);return}if(busy())return;const L=[{id:'first-gather',when:(s.forest||0)>0||(s.quarry||0)>0,question:'¿Entendiste por qué estabas recolectando?'},{id:'first-major-combat',when:!!(s.boss||s.corruptResidue),question:'¿Este combate te resultó claro?',reasons:['No entendí qué decidía yo','No entendí por qué gané o perdí','No entendí la recompensa','Otro']},{id:'first-hero',when:!!s.lyra,question:'¿Te interesa mejorar este héroe?',reasons:['No entiendo para qué sirve','No me interesa progresarlo','No veo diferencias con las tropas','Otro']},{id:'first-relic',when:!!s.codexUnlocked&&(s.codex||[]).length>0,question:'¿Te gustaría encontrar más cartas?',reasons:['No entiendo para qué sirven','No me interesa coleccionarlas','El Códice me resulta confuso','Otro']},{id:'first-duel',when:!!s.duelTutorialComplete,question:'¿El Duelo de Reliquias te resultó claro?',reasons:['No entendí N/E/S/O','No entendí las capturas','No entendí qué ganaba','Otro']}],x=L.find(v=>v.when&&!asked(v.id));if(x)ask(x)}
window.addEventListener('error',e=>ERR.push({at:Date.now(),type:'error',message:e.message||'Error',source:e.filename||null,line:e.lineno||null}));window.addEventListener('unhandledrejection',e=>ERR.push({at:Date.now(),type:'promise',message:String(e.reason?.message||e.reason||'Rejected promise')}));
document.addEventListener('click',e=>{const t=e.target.closest?.('button,[data-node],[data-poi],[data-nav],[data-object-action]');if(!t)return;last={type:'tap',label:(t.innerText||t.getAttribute('aria-label')||t.dataset.node||t.dataset.poi||t.dataset.nav||t.dataset.objectAction||'acción').trim().slice(0,120),node:t.dataset.node||null,poi:t.dataset.poi||null,testid:t.dataset.testid||t.getAttribute('data-testid')||null,at:Date.now()}},{capture:true});
window.addEventListener('online',flush);
function init(){if(!document.getElementById('eldoria-tester-style'))styles();fab();watchFinal();intro();setInterval(poll,1200);setInterval(flush,15000);setTimeout(flush,2500)}
window.ELDORIA_TESTER={config:C,state:st,context:context,submit:submit,flush:flush,queue:queue,ask:ask,openHelp:help,openFinal:()=>{let h=document.querySelector('[data-testid="playtest-complete"]');if(!h)h=ov('<div></div>','testerManualFinal');finalMounted=false;final(h)},resetTester:()=>{localStorage.removeItem(IK);localStorage.removeItem(AK);localStorage.removeItem(QK)},version:'1.0.0'};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,50));else setTimeout(init,50);
})();