using Eldoria.Domain;using UnityEngine;using Object=UnityEngine.Object;
namespace Eldoria.Presentation {
public static class ValoriaProductionDensityLifeV1 {
 public static bool Enabled=false;public static int Props,Trees;
 public static void Apply(Transform root,PlayerState state){if(!Enabled||root==null)return;Props=Trees=0;BuildTrees(root);BuildProps(root);}
 static void BuildTrees(Transform root){var a=Resources.Load<GameObject>("WorldInventory/Tree01A");var b=Resources.Load<GameObject>("WorldInventory/Tree01B");if(a==null&&b==null)return;var s=new[]{new Vector4(-8.0f,1.8f,18,.78f),new Vector4(8.0f,1.8f,-18,.76f),new Vector4(-6.7f,5.6f,30,.92f),new Vector4(6.6f,5.5f,-24,.92f),new Vector4(-2.8f,7.0f,8,.78f),new Vector4(2.8f,7.0f,-8,.80f),new Vector4(-12.0f,12.2f,20,1.18f),new Vector4(12.0f,12.2f,-20,1.18f)};for(int i=0;i<s.Length;i++){var v=s[i];var src=(i%2==0?a:b)??a??b;var go=ValoriaKit.BenchmarkPiece("Valoria · Production Density · tree",src,new Vector3(v.x,.12f,v.y),v.w,v.w*2.9f,Quaternion.Euler(0,v.z,0));if(go!=null){go.transform.SetParent(root,true);Strip(go);Trees++;}}}
 static void BuildProps(Transform root){var barrel=Resources.Load<GameObject>("Valoria/UrbanProps/Barrel");var crate=Resources.Load<GameObject>("Valoria/UrbanProps/Crate");var sack=Resources.Load<GameObject>("Valoria/UrbanProps/Sack");Place(root,barrel,new Vector3(-6.8f,.14f,-2.7f),.44f,12);Place(root,crate,new Vector3(-6.3f,.14f,-2.9f),.50f,-14);Place(root,crate,new Vector3(6.3f,.14f,-3.0f),.48f,12);Place(root,barrel,new Vector3(6.8f,.14f,-3.2f),.43f,-8);Place(root,sack,new Vector3(-1.5f,.14f,-4.9f),.52f,10);Place(root,sack,new Vector3(-1.1f,.14f,-4.8f),.48f,-12);}
 static void Place(Transform root,GameObject src,Vector3 p,float f,float yaw){if(src==null)return;var go=ValoriaKit.BenchmarkPiece("Valoria · Production Density · functional prop",src,p,f,f*1.25f,Quaternion.Euler(0,yaw,0));if(go!=null){go.transform.SetParent(root,true);Strip(go);Props++;}}
 static void Strip(GameObject go){foreach(var c in go.GetComponentsInChildren<Collider>(true))Object.DestroyImmediate(c);foreach(var h in go.GetComponentsInChildren<WorldHotspot>(true))Object.DestroyImmediate(h);}
}}