import test from 'node:test';
import assert from 'node:assert/strict';
import {certify,GATES} from '../../tools/m03/certify.mjs';
import {verifyGitHub,evaluateM16Verified} from '../../tools/m03/github-evidence.mjs';
const S='a'.repeat(40),D='b'.repeat(64),repo='mt5hjfz2kb-lab/Eldoria-Prewiu';
function certificate(){const candidate={schema_version:1,id:'M16-A',source_sha:S,build_id:'b',build_sha256:D,artifact_id:'42',executor_id:'builder',built_at:'2026-10-08T10:00:00Z'};const requirements=Object.fromEntries(GATES.map(g=>[g,{required:g==='TECH',scenarios:g==='TECH'?['check']:[]}]));const policy={schema_version:1,id:'p',version:1,frozen_at:'2026-10-08T09:00:00Z',frozen_for_sha:S,required_gates:['TECH'],requirements};const evidence=[{id:'1',gate:'TECH',scenario:'check',result:'PASS',source_sha:S,build_id:'b',build_sha256:D,artifact_id:'42',producer_id:'qa',provenance:'CI',run_id:'12',reference:'https://github.com/example',observed_at:'2026-10-08T10:10:00Z',expires_at:'2026-10-09T10:10:00Z'}];return certify({candidate,policy,evidence,now:'2026-10-08T12:00:00Z'});}
const reader=(run={},artifact={})=>async url=>url.includes('/commits/')?{sha:S}:url.includes('/artifacts?')?{total_count:1,artifacts:[{id:42,expired:false,digest:'sha256:'+D,workflow_run:{id:12,head_sha:S},...artifact}]}:{id:12,head_sha:S,status:'completed',conclusion:'success',repository:{full_name:repo},...run};
test('valid matching provider metadata',async()=>assert.equal((await verifyGitHub(certificate(),{repository:repo,reader:reader()})).verified,true));
test('cancelled run blocks',async()=>assert.equal((await verifyGitHub(certificate(),{repository:repo,reader:reader({conclusion:'cancelled'})})).verified,false));
test('wrong commit SHA blocks',async()=>assert.equal((await verifyGitHub(certificate(),{repository:repo,reader:reader({head_sha:'c'.repeat(40)})})).verified,false));
test('artifact expired blocks',async()=>assert.equal((await verifyGitHub(certificate(),{repository:repo,reader:reader({},{expired:true})})).verified,false));
test('artifact digest mismatch blocks',async()=>assert.equal((await verifyGitHub(certificate(),{repository:repo,reader:reader({},{digest:'sha256:'+'c'.repeat(64)})})).verified,false));
test('provider outage fails closed',async()=>assert.equal((await verifyGitHub(certificate(),{repository:repo,reader:async()=>{throw Error('offline')}})).verified,false));
test('duplicate verification is deterministic',async()=>{const c=certificate(),a=await verifyGitHub(c,{repository:repo,reader:reader()}),b=await verifyGitHub(c,{repository:repo,reader:reader()});assert.deepEqual(a,b)});
test('M16 blocks unverified provider certificate',async()=>{const catalog={schema_version:1,departments:[{id:'qa',capabilities:['github_workflow']}],jobs:[{id:'M16-A',department:'qa',status:'APPROVED',executor:'github_workflow',acceptance_policy:'m03',certificate_id:'cert',depends_on:[],scopes:[],resources:[]},{id:'M16-B',department:'qa',status:'APPROVED',executor:'github_workflow',acceptance_policy:'m03',depends_on:[{job_id:'M16-A',required_gate:'TECH',certificate_id:'cert'}],scopes:[],resources:[]}]};const c={...certificate(),id:'cert'};let r=await evaluateM16Verified(catalog,{active:[]},[c],{repository:repo,reader:reader({conclusion:'failure'})});assert.equal(r.results[1].readiness,'BLOCKED')});
