const P=(a,b)=>{if(!base.includes(a))throw new Error('r7 patch missing: '+a.slice(0,60));base=base.replace(a,b)};
P("  let chapterBuildTimer = null;","  let chapterBuildTimer = null;\n  const BUILD = '0.19.5-r7';\n  const prefersReducedMotion = () => window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;\n  const pacedDelay = ms => prefersReducedMotion() ? Math.min(ms,120) : ms;");
P("version:'0.19.5-r6'","version:BUILD");
P("setTimeout(()=>{if(!modal)showIntro();},350); else if(state.introSeen&&!state.chapter1Complete&&!currentChapter1Building()) setTimeout(()=>{if(!modal)finishChapter1();},350); else if(state.chapter1Complete&&!state.chapter2Started) setTimeout(()=>{if(!modal)startChapter2();},350);","setTimeout(()=>{if(!modal)showIntro();},pacedDelay(350)); else if(state.introSeen&&!state.chapter1Complete&&!currentChapter1Building()) setTimeout(()=>{if(!modal)finishChapter1();},pacedDelay(350)); else if(state.chapter1Complete&&!state.chapter2Started) setTimeout(()=>{if(!modal)startChapter2();},pacedDelay(350));");
P("La corona desapareció. Las murallas resisten, pero el reino se apaga.","La corona desapareció. Valoria resiste entre cenizas.");
P("Una herida violeta corrompe bosques, criaturas y caminos. Nadie conoce todavía su origen.","Una herida violeta está deformando el mundo. Nadie conoce su origen.");
P("Los edificios principales son ruinas. Devuélvelos a la vida uno a uno y aprende qué sostiene tu reino.","Levanta de nuevo lo esencial. Después cruzaremos las puertas.");
P("const duration=1800;","const duration=prefersReducedMotion()?120:1200;");
P("Reconstruir lleva tiempo. En el juego final, cada estructura tendrá su propia duración.","Valoria cambia con cada reconstrucción.");
P('id="build-seconds">2 s','id="build-seconds">1 s');
P("},1100);","},pacedDelay(900));");
P("Valoria vuelve a sostenerse. Ahora debes aprender a fortalecerla, cruzar sus puertas y descubrir qué ocurre fuera.","Valoria vuelve a sostenerse. Fortalécela una vez más y cruza las puertas.");
P("El Granero funciona, pero puede dar más. Mejóralo y después saldremos al mundo.","Mejora el Granero. Después salimos.");
P('id="upgrade" class="primary">Mejorar ahora','id="upgrade" data-testid="upgrade-building" class="primary">Mejorar ahora');
P('id="begin-auto" class="primary">Comenzar batalla semiautomática','id="begin-auto" data-testid="begin-auto-combat" class="primary">Comenzar batalla semiautomática');
P("openModal('Informe del Capítulo I'","openModal('Encuesta final de la prueba'");
P('id="claim" class="primary">Guardar en el Archivo','id="claim" data-testid="claim-first-card" class="primary">Guardar en el Archivo');
P('id="equip-relic" class="primary">Equipar reliquia','id="equip-relic" data-testid="equip-relic" class="primary">Equipar reliquia');
P('id="equipment-continue" class="primary">Continuar','id="equipment-continue" data-testid="equipment-continue" class="primary">Continuar');
P("El total mide el desarrollo de tu cuenta. <strong>No decide el resultado de un combate:</strong> la expedición depende de quién marcha, sus tropas, habilidades, cartas y preparación.","Tu Poder resume el progreso. En expedición importan también héroes, tropas y preparación.");
P('id="close-power" class="secondary">Cerrar','id="close-power" data-testid="close-power" class="secondary">Cerrar');
base=base.replaceAll('id="enemy" class="enemy objective"','id="enemy" data-testid="expedition-enemy" class="enemy objective"').replaceAll('id="return" class="return"','id="return" data-testid="return-kingdom" class="return"');
P("setTimeout(()=>{march.remove();done();},1750);","setTimeout(()=>{march.remove();done();},pacedDelay(900));");
const css=`\n/* v0.19.5 r7 polish */\nbutton:focus-visible{outline:2px solid currentColor;outline-offset:3px}.modal{overscroll-behavior:contain}.reward-modal{animation:rewardArrival .32s cubic-bezier(.2,.9,.25,1.15)}@keyframes rewardArrival{from{transform:translateY(12px) scale(.985);opacity:.4}to{transform:none;opacity:1}}.building.level-up,.future-signal,.gate.objective{will-change:transform,filter}.gate.objective{animation:objectivePulse 1.8s ease-in-out infinite}@keyframes objectivePulse{50%{filter:drop-shadow(0 0 13px rgba(215,180,91,.52));transform:translateY(-2px)}}.screen-feedback.power,.screen-feedback.heal{font-weight:800;letter-spacing:.02em}@media(max-width:430px){.modal{max-height:88dvh;overflow:auto}.combat-actions{position:sticky;bottom:0;z-index:3;padding-bottom:max(8px,env(safe-area-inset-bottom));backdrop-filter:blur(8px)}.intent-choices button{min-height:68px}.hero-unit{scroll-margin-top:12px}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important;scroll-behavior:auto!important}}\n`;
base=base.replace('</style>',css+'</style>');
