import fs from 'node:fs';
import path from 'node:path';
const p=path.join(process.cwd(),'playtest','index.html');
let h=fs.readFileSync(p,'utf8');
const css=`<style id="v0201-ux">
:root{--guide:#e7c878;--safe:#79d89b}.v020-focus{outline:3px solid var(--guide)!important;outline-offset:4px!important;box-shadow:0 0 0 7px rgba(231,200,120,.16),0 0 28px rgba(231,200,120,.38)!important;animation:v020pulse 1.6s ease-in-out infinite}.v020-locked{opacity:.42!important;filter:grayscale(.75);pointer-events:none!important}.v020-locked::after{content:'🔒 Se desbloquea durante la historia';display:block;font-size:10px;margin-top:4px}.v020-toast{position:fixed;left:50%;bottom:calc(78px + env(safe-area-inset-bottom));transform:translateX(-50%);z-index:10020;min-width:min(330px,88vw);padding:14px 18px;border:1px solid rgba(231,200,120,.55);border-radius:14px;background:rgba(18,16,20,.97);box-shadow:0 16px 45px #0009;text-align:center}.v020-toast b{color:var(--guide);font-size:18px}.v020-resource-help{position:fixed;top:calc(8px + env(safe-area-inset-top));left:50%;transform:translateX(-50%);z-index:9000;padding:6px 10px;border-radius:10px;background:#111c;border:1px solid #ffffff20;font-size:10px;pointer-events:none}.v020-hero-silhouette{background:radial-gradient(circle at 50% 30%,#9b8b73 0 15%,#4b4239 16% 32%,#1b1819 33%);border:2px solid #b99658!important;position:relative}.v020-hero-silhouette::after{content:'SIR ALDRIC';position:absolute;bottom:5px;left:0;right:0;font-size:8px;letter-spacing:.1em;color:#e7c878;text-align:center}.v020-reveal{animation:v020reveal 1.2s ease-out}.v020-mission-open{max-height:none!important;height:auto!important;overflow:visible!important;opacity:1!important;visibility:visible!important}.v020-explain{margin:10px 0;padding:10px 12px;border-left:3px solid var(--guide);background:#e7c8780d;font-size:12px;line-height:1.45}.v020-safe-tag{font-weight:900!important;font-size:1.12em!important;color:#dfffea!important}.v020-safe-tag::after{content:'  ← EMPIEZA AQUÍ';font-size:9px;color:var(--safe)}.duel-cell.player{box-shadow:inset 0 0 0 2px rgba(215,180,91,.34)!important}.duel-cell.cpu{box-shadow:inset 0 0 0 2px rgba(167,79,209,.34)!important}@keyframes v020pulse{50%{filter:brightness(1.18)}}@keyframes v020reveal{0%{transform:scale(.7);filter:brightness(3);opacity:0}65%{transform:scale(1.06)}100%{transform:none;filter:none;opacity:1}}@media(max-width:430px){.v020-focus{outline-width:2px!important}.v020-resource-help{font-size:9px;max-width:94vw;white-space:nowrap}.v020-explain{font-size:11px}}
</style>`;
const js=`<script id="v0201-ux-script">(()=>{
const S={archive:false,worldIntro:false};try{Object.assign(S,JSON.parse(localStorage.getItem('eldoria-v0201-ux')||'{}'))}catch{};const save=()=>localStorage.setItem('eldoria-v0201-ux',JSON.stringify(S));
const txt=e=>(e?.innerText||e?.textContent||'').trim();const all=s=>[...document.querySelectorAll(s)];
function toast(html,ms=2400){const t=document.createElement('div');t.className='v020-toast';t.innerHTML=html;document.body.appendChild(t);setTimeout(()=>t.remove(),ms)}
function resourceLegend(){if(document.querySelector('.v020-resource-help'))return;const candidates=all('header,nav,.topbar,.hud,.resources').filter(e=>/madera|piedra|comida|oro|recurso/i.test(txt(e)));if(candidates.length)return;const d=document.createElement('div');d.className='v020-resource-help';d.textContent='🌾 Comida  ·  🪵 Madera  ·  🪨 Piedra  ·  ✦ Esencia';document.body.appendChild(d)}
function missions(){all('button,[role=button],.mission,.quest').forEach(e=>{if(/misiones|objetivos|misión/i.test(txt(e))){e.style.pointerEvents='auto';e.classList.add('v020-mission-open')}})}
function archive(){const unlocked=/primera carta|guardar en el archivo|reliquia|archivo de reliquias/i.test(document.body.innerText);if(unlocked)S.archive=true;all('button,a,[role=button]').forEach(e=>{if(/^archivo$|archivo de reliquias/i.test(txt(e))){e.classList.toggle('v020-locked',!S.archive);e.setAttribute('aria-disabled',S.archive?'false':'true')}});save()}
function heroHall(){const body=document.body.innerText;if(!/salón de héroes/i.test(body))return;all('.hero,.hero-card,.slot,[class*=hero]').forEach((e,i)=>{if(i===0&&!/aldric/i.test(txt(e)))e.classList.add('v020-hero-silhouette')});const modal=all('.modal,.panel,.card').find(e=>/salón de héroes/i.test(txt(e)));if(modal&&!modal.querySelector('.v020-explain')){const x=document.createElement('div');x.className='v020-explain';x.innerHTML='<b>Héroes</b> · Ganan <b>XP</b> para subir de nivel. La <b>Esencia</b> mejora habilidades. Las <b>Resonancias</b> son especializaciones: cambian el papel del héroe y serán decisiones importantes de construcción.';modal.appendChild(x)}}
function world(){if(!/bosque seguro/i.test(document.body.innerText))return;S.worldIntro=true;all('button,.node,[role=button],.poi').forEach(e=>{if(/bosque seguro/i.test(txt(e))){e.classList.add('v020-focus','v020-safe-tag');e.scrollIntoView?.({block:'center',inline:'center',behavior:'smooth'})}});save()}
function pacing(){const text=document.body.innerText;if(/segundo héroe|nuevo héroe|se une/i.test(text)&&!sessionStorage.v020HeroReveal){sessionStorage.v020HeroReveal='1';const m=all('.modal,.panel').find(e=>/héroe/i.test(txt(e)));m?.classList.add('v020-reveal');toast('<b>✦ NUEVO HÉROE</b><br>Un nuevo campeón se une a Valoria',2600)}if(/fragmentos? del núcleo/i.test(text)&&!sessionStorage.v020Core){sessionStorage.v020Core='1';toast('<b>Fragmentos del Núcleo</b><br>Material de la Brecha. Consérvalo: su poder se explicará antes de utilizarlo.',3000)}}
function duel(){if(!/duelo de reliquias/i.test(document.body.innerText))return;const modal=all('.modal,.panel,.card').find(e=>/duelo de reliquias/i.test(txt(e)));if(modal&&!modal.querySelector('.v020-explain')){const x=document.createElement('div');x.className='v020-explain';x.innerHTML='<b>Reliquias coleccionables</b> · Tu colección crecerá durante las expediciones. Antes de cada Duelo eliges <b>5 reliquias</b> para tu mazo. Cada carta tiene valores <b>N / E / S / O</b>: al colocarla, el valor que mira a la carta vecina compite con su lado enfrentado. Si ganas, la capturas.<br><br><b>Este sistema está diseñado para duelos PvP.</b> En este vertical slice, Orin actúa como rival controlado por el juego.';modal.prepend(x)}}
function contextual(){all('.modal,.panel,.quest').forEach(e=>{const t=txt(e);if(/resonancia/i.test(t)&&!e.querySelector('.v020-explain')){const d=document.createElement('div');d.className='v020-explain';d.innerHTML='<b>¿Por qué importa?</b> Una Resonancia especializa al héroe. No es una mejora numérica cualquiera: orienta cómo rendirá y qué sinergias tendrá.';e.appendChild(d)}})}
function run(){resourceLegend();missions();archive();heroHall();world();pacing();duel();contextual()};let q;new MutationObserver(()=>{clearTimeout(q);q=setTimeout(run,120)}).observe(document.documentElement,{subtree:true,childList:true,characterData:true});setTimeout(run,400)
})();</script>`;
h=h.replace('</head>',css+'</head>').replace('</body>',js+'</body>').replaceAll('0.19.5-r7-storypass','0.20.1-onboarding');
h=h.replace("setTimeout(()=>{march.remove();done();},1750);","setTimeout(()=>{march.remove();done();},2800);");
h=h.replace('<head>','<head><meta name="eldoria-canonical-base" content="0.20.1-consolidated">');
fs.writeFileSync(p,h);console.log('Applied Eldoria v0.20.1 real-state onboarding pass');
